# === Dataset ===
data_path: "data/raw.csv"

# === Model saving ===
model_dir: "models"
model_name: "model.pkl"

# === Train parameters ===
train:
  test_size: 0.2
  random_state: 42

# === Model ===
model:
  type: "LogisticRegression"
  params:
    max_iter: 1000
    solver: "lbfgs"

# === GridSearch ===
gridsearch:
  cv: 5
  scoring: "accuracy"
  param_grid:
    C: [0.01, 0.1, 1, 10]    # régularisation
    penalty: ["l2"]

# === MLflow ===
mlflow:
  experiment_name: "churn-classification"
  tracking_uri: "http://127.0.0.1:5000"
